### ISSUE TITLE
skyway & goo API叩く

### ISSUE THREAD

**Issue by butaosuinu** [jphacks/HK_1601#2]

**Comment by ghost** [comment]
SkyWayの音声認識は確認済み

**Comment by butaosuinu** [comment]
クライアントはPOSTでSkyway通した後の検出された語句をサーバに送信する

**Comment by butaosuinu** [comment]
サーバはPOSTされた語句を元にgooAPI叩いて語句を解析、filterに通してかかったものは統計に。  
統計から閾値超えていたらクライアントに通知を送りそれをトリガーに癒やしコンテンツ等を流す。

**Comment by ghost** [comment]
音声認識やることは大体できました。
